In [1]:
import numpy as np

In [2]:
minha_lista=[1,2,3]

In [5]:
minha_lista

[1, 2, 3]

In [6]:
matriz=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [11]:
arr = np.zeros((5,5)) #(5,5) é uma tupla que defini as dimensões da matriz

In [12]:
arr

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [13]:
np.eye(4) #matriz identidade

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [14]:
 np.linspace(0,10,4)

array([  0.        ,   3.33333333,   6.66666667,  10.        ])

In [16]:
np.random.randint(0,100,12) *100

array([   0,  300, 6500, 7800, 8600, 6000, 3500, 6300, 7200, 7300, 8500,
       6200])

In [18]:
vet = np.random.rand(25)

In [19]:
vet = vet.reshape((5,5)) #tupla que muda etrutura 'shape' do vet

In [20]:
vet

array([[ 0.46863407,  0.88275742,  0.250346  ,  0.0106524 ,  0.41348194],
       [ 0.72017518,  0.81075214,  0.78882997,  0.27024531,  0.72852629],
       [ 0.19742442,  0.46594537,  0.01690766,  0.75861241,  0.98990416],
       [ 0.3207659 ,  0.89488558,  0.65655442,  0.76449518,  0.76630643],
       [ 0.71379418,  0.57640547,  0.26516477,  0.39429123,  0.28254696]])

## indexação e fatiamento de arrays - aula 5

In [22]:
arr = np.arange(0,30,3)

In [23]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [24]:
arr[3]

9

In [25]:
arr[2:5]

array([ 6,  9, 12])

In [27]:
arr[2:-3] = 10

In [28]:
arr

array([ 0,  3, 10, 10, 10, 10, 10, 21, 24, 27])

In [33]:
arr2 = arr[:3] # arr2 aponta para arr

In [34]:
arr2

array([ 0,  3, 10])

In [36]:
arr2[:]= 123

In [37]:
arr2

array([123, 123, 123])

In [38]:
arr

array([123, 123, 123,  10,  10,  10,  10,  21,  24,  27])

In [42]:
arr3 = arr[:3].copy() # agora sim, faz um COPIA sem ser um ponteiro

In [43]:
arr3

array([123, 123, 123])

In [44]:
mat = np.linspace(0,500, 50)

In [45]:
mat.reshape(5,10)

array([[   0.        ,   10.20408163,   20.40816327,   30.6122449 ,
          40.81632653,   51.02040816,   61.2244898 ,   71.42857143,
          81.63265306,   91.83673469],
       [ 102.04081633,  112.24489796,  122.44897959,  132.65306122,
         142.85714286,  153.06122449,  163.26530612,  173.46938776,
         183.67346939,  193.87755102],
       [ 204.08163265,  214.28571429,  224.48979592,  234.69387755,
         244.89795918,  255.10204082,  265.30612245,  275.51020408,
         285.71428571,  295.91836735],
       [ 306.12244898,  316.32653061,  326.53061224,  336.73469388,
         346.93877551,  357.14285714,  367.34693878,  377.55102041,
         387.75510204,  397.95918367],
       [ 408.16326531,  418.36734694,  428.57142857,  438.7755102 ,
         448.97959184,  459.18367347,  469.3877551 ,  479.59183673,
         489.79591837,  500.        ]])

In [51]:
boo = mat > 44

In [52]:
boo

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True], dtype=bool)

In [53]:
mat[boo]

array([  51.02040816,   61.2244898 ,   71.42857143,   81.63265306,
         91.83673469,  102.04081633,  112.24489796,  122.44897959,
        132.65306122,  142.85714286,  153.06122449,  163.26530612,
        173.46938776,  183.67346939,  193.87755102,  204.08163265,
        214.28571429,  224.48979592,  234.69387755,  244.89795918,
        255.10204082,  265.30612245,  275.51020408,  285.71428571,
        295.91836735,  306.12244898,  316.32653061,  326.53061224,
        336.73469388,  346.93877551,  357.14285714,  367.34693878,
        377.55102041,  387.75510204,  397.95918367,  408.16326531,
        418.36734694,  428.57142857,  438.7755102 ,  448.97959184,
        459.18367347,  469.3877551 ,  479.59183673,  489.79591837,  500.        ])

In [54]:
mat

array([   0.        ,   10.20408163,   20.40816327,   30.6122449 ,
         40.81632653,   51.02040816,   61.2244898 ,   71.42857143,
         81.63265306,   91.83673469,  102.04081633,  112.24489796,
        122.44897959,  132.65306122,  142.85714286,  153.06122449,
        163.26530612,  173.46938776,  183.67346939,  193.87755102,
        204.08163265,  214.28571429,  224.48979592,  234.69387755,
        244.89795918,  255.10204082,  265.30612245,  275.51020408,
        285.71428571,  295.91836735,  306.12244898,  316.32653061,
        326.53061224,  336.73469388,  346.93877551,  357.14285714,
        367.34693878,  377.55102041,  387.75510204,  397.95918367,
        408.16326531,  418.36734694,  428.57142857,  438.7755102 ,
        448.97959184,  459.18367347,  469.3877551 ,  479.59183673,
        489.79591837,  500.        ])

In [59]:
mat = mat.reshape(5,10)

In [60]:
mat[0:2, 3]

array([  30.6122449 ,  132.65306122])

# Exercicios Numpy

In [61]:
import numpy as np

In [62]:
mt = np.zeros(10)

In [63]:
mt

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [64]:
mt +=1

In [65]:
mt

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [66]:
mt5 = np.zeros(10)+5

In [67]:
mt5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [68]:
mt_int = np.arange(10, 51, 2)

In [69]:
mt_int

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [70]:
mt = np.arange(0,9).reshape(3,3)

In [71]:
mt

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
arr = np.random.rand(25)

In [73]:
arr

array([ 0.42986307,  0.03313766,  0.91379715,  0.29663768,  0.13507511,
        0.26370194,  0.47591037,  0.93801   ,  0.85648696,  0.15819508,
        0.69634979,  0.2715046 ,  0.10418035,  0.41064373,  0.47553645,
        0.54441645,  0.13051252,  0.90802553,  0.52691187,  0.52172109,
        0.03804624,  0.63211236,  0.46557381,  0.4960297 ,  0.77674233])

In [80]:
arr = np.arange(1,101).reshape(10,10)/100

In [82]:
ar20 = np.linspace(0,1,20)

In [83]:
ar20

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [84]:
mat = np.arange(1,26).reshape(5,5)

In [85]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [89]:
mat[3,4]

20

In [92]:
mat[0:3, 1]

array([ 2,  7, 12])

In [94]:
mat.sum()

325

In [95]:
mat.sum(axis=0) # soma de todas as colunas

array([55, 60, 65, 70, 75])